### ISSUE TITLE
Question about the codes

### ISSUE THREAD

**Issue by minwoo0611** [hku-mars/STD#9]
I am a Master's student from Korea, and I would like to express my appreciation for sharing the code with the community. I have carefully studied the HKU-MARS studies, and I have a question regarding the extraction of corner points.

I would like to inquire about two aspects of the code:

 1. In lines 780 to 805, I am not sure if the variables in this section are being utilized, as it seems that the code is using the maximum of img_count_array[x_index][y_index] instead of the gradient (line 807 to 834). Can you please confirm if this section of the code is indeed being used?

2. In lines 837 to 884, it appears that the code is filtering lines in the image from the voxel, and the values of neighboring pixels should be similar if a line is present. The condition (img_count_array[p1[0]][p1[1]] >= threshold && img_count_array[p2[0]][p2[1]] >= threshold) is used to find lines, not corner points. However, it seems that the code is repurposing the line filtering step to identify corner points. Therefore, I would like to ask if uncommenting the line in 856, which is "is_add = false," would be the right approach to filter out lines and retain only the corner points.

Thank you for your kind attention, and I look forward to your response.

Best regards,
Minwoo Jung

**Comment by ChongjianYUAN** [comment]
> 1. In lines 780 to 805, I am not sure if the variables in this section are being utilized, as it seems that the code is using the maximum of img_count_array[x_index][y_index] instead of the gradient (line 807 to 834). Can you please confirm if this section of the code is indeed being used?

Thanks for your attention. 
1.  The code is using the maximum of img_count_array[x_index][y_index] instead of the gradient. In our tests, these two worked fairly well. We also tried some other schemes (such as max distance etc.). The current corner point extraction strategy is a temporary version and is not continued to be used in our extended version.
2.  When uncommenting the line in 856,  the code will filter out corner points on the lines. But this step is still not stable enough, so it is not enabled.
